### PR TITLE
ksmbd-tools: fix unused variable value

### PR DESCRIPTION
**Pull request by neheb**
ret is default initialized to 0.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by namjaejeon** [comment]
@neheb I can not understand why this patch is needed.

**Comment by neheb** [comment]
code is basically

```
int ret = 0;
ret = x;
```

0 is an unused value. The other way to fix it is to get rid of the 0.

**Comment by namjaejeon** [comment]
> The other way to fix it is to get rid of the 0.

@neheb Right, That is what I want.

**Comment by neheb** [comment]
Done.

**Comment by atheik** [comment]
@neheb,

You are now returning an uninitialized value:

https://github.com/cifsd-team/ksmbd-tools/blob/84f6ef443aa0bf28177fb7b5d1fa6316a00a401b/tools/config_parser.c#L639-L646

**Comment by neheb** [comment]
Which indicates my original solution was better

**Comment by namjaejeon** [comment]
@neheb @atheik  Ah, Sorry. In my opinion, I think original patch is even not needed...

**Comment by namjaejeon** [comment]
@neheb if you have other opinion, I am going to close this PR.

**Pull request closed without merging**
