### PR TITLE
Make options mutually exclusive for ksmbd.control

### PR DESCRIPTION
**Pull request by atheik**
ksmbd-tools: add missing component to usage string of ksmbd.control
ksmbd-tools: make options mutually exclusive for ksmbd.control

Signed-off-by: atheik \<atteh.mailbox@gmail.com>

### CODE REVIEW

**Comment by atheik** [comment]
@namjaejeon, actually this might a bug in the new usage string.

Before 47d93fc: Only the shutdown, debug, and ksmbd-version options can appear
in any order, and their repetition is not ignored.
After 47d93fc: All options can appear in any order, and their repetition is not ignored.
After PR: All options are mutually exclusive and repetition is ignored.

Is the following an intended use case?
```
# control/ksmbd.control -d smb -d vfs -d ipc -d rdma
[ksmbd.control/5797]: INFO: [smb] auth vfs oplock ipc conn rdma 

[ksmbd.control/5797]: INFO: [smb] auth [vfs] oplock ipc conn rdma 

[ksmbd.control/5797]: INFO: [smb] auth [vfs] oplock [ipc] conn rdma 

[ksmbd.control/5797]: INFO: [smb] auth [vfs] oplock [ipc] conn [rdma] 

```

**Comment by namjaejeon** [comment]
> Is the following an intended use case?

No, I didn't intend to. BTW, if options are not mutually exclusive, What will be a problem ?

**Comment by atheik** [comment]
@namjaejeon, it's confusing. When they are not mutually exclusive, only help and version options stop argument handling:
```
# /usr/local/sbin/ksmbd.control -d all -c -c -V -c -c -c -c -c -c -c -c
[ksmbd.control/6965]: INFO: [smb] [auth] [vfs] [oplock] [ipc] [conn] [rdma] 

[ksmbd.control/6965]: INFO: ksmbd version : 3.4.2

[ksmbd.control/6965]: INFO: ksmbd version : 3.4.2

ksmbd-tools version : 3.4.5
```
When they are mutually exclusive:
```
# /usr/local/sbin/ksmbd.control -d all -c -c -V -c -c -c -c -c -c -c -c
[ksmbd.control/6965]: INFO: [smb] [auth] [vfs] [oplock] [ipc] [conn] [rdma] 

```
If you prefer that all options are mutually exclusive, then merge this PR.
Otherwise, tell me and I will then remove the latest commit from this PR and rewrite the usage string.

**Comment by atheik** [comment]
@namjaejeon, this isn't a problem for the other programs since their mutually exclusive options (add-\*, update-\*, and del-\*) don't print anything in the getopt_long() loop. If add-user, update-user, and del-user are all given to ksmbd.adduser, the option that gets applied is the one that is given last and the user doesn't see argument handling for the preceding options. This isn't the case for ksmbd.control, which prints in the getopt_long() loop. That's why I think all options that print in the getopt_long() loop of ksmbd.control should be made mutually exclusive (stop further argument handling). Since you hadn't intended that the debug option can be repeated, I don't think there is any reason why the options shouldn't be mutually exclusive.

**Comment by namjaejeon** [comment]
@atheik make sense. thanks for your work!

**Comment by namjaejeon** [comment]
Applied, thanks for your work!

**Pull request closed without merging**
