### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by atheik**
ksmbd-tools: fix process exit codes
ksmbd-tools: replace setsid with setpgid in nodetach mode
ksmbd-tools: reformat markdown readme
ksmbd-tools: add reload option to ksmbd.control
ksmbd-tools: move lock file to runstatedir
ksmbd-tools: derive subauth filename from config filename

Is `ksmbd-tools: derive subauth filename from config filename` a good idea?
Or is there no deeper reason why the subauth file is written to the same directory as the config file?

As a side note, `create_lock_file()` doesn't return negated errno when failing to write manager pid.
https://github.com/cifsd-team/ksmbd-tools/blob/4608cd4/mountd/mountd.c#L127-L129
Is this a bug?

Signed-off-by: atheik \<atteh.mailbox@gmail.com>

### CODE REVIEW

**Comment by namjaejeon** [comment]
@atheik Totally looks good to me:)

1. You remove README file. when commanding make dist, there is no README(even README.md) in ksmbd-tools-version.tgz. We need to add README.md in EXTRA_DIST.

2. there is no default path for --with-rundir ? Can we make default rundir path to /run ? Normally users will not use this option. @neheb is there /run(tmpfs) in openWRT system ?

> Is ksmbd-tools: derive subauth filename from config filename a good idea?
I could just not find where subauth file is located before. If this file is located in /var/ or /tmp or the other, It can be removed.  The subauth value had to be stored in persistent storage as it should always remain the same. In other words, it should not be changed every time ksmbd.mountd is run, it should be created only on the first run. Hm.. I have no idea why subauth is changed with config filename. ksmbd.mountd cannot be multiply run on the same server as per config filename.

**Comment by namjaejeon** [comment]
> create_lock_file() doesn't return negated errno when failing to write manager pid.

Yes. I think we can handle it more strictly.

**Comment by neheb** [comment]
>     2. there is no default path for --with-rundir ? Can we make default rundir path to /run ? Normally users will not use this option. @neheb is there /run(tmpfs) in openWRT system ?

No. There's /var/run as well as /tmp. /run probably should be added though...

**Comment by namjaejeon** [comment]
@atheik The best way is to find a way to keep a unique subauth value without creating a subauth file. How about using the checksum of the hostname?

**Comment by namjaejeon** [comment]
@neheb Thanks for your answer:)

**Comment by atheik** [comment]
@namjaejeon,

> @atheik Totally looks good to me:)
> 
> 1. You remove README file. when commanding make dist, there is no README(even README.md) in ksmbd-tools-version.tgz. We need to add README.md in EXTRA_DIST.

Oops. Good catch.

> 2. there is no default path for --with-rundir ? Can we make default rundir path to /run ? Normally users will not use this option. @neheb is there /run(tmpfs) in openWRT system ?
> 

Both `--with-rundir` and `-Drundir` have a default value regardless of whether `--runstatedir` is available. If `--runstatedir` is not available, it is `$(prefix)/$(localstatedir)/run`. The reason why I explicitly set it to `/run` in the README is that it cannot be created in the `install` target and `/run` is typically available. It is often the case `/var/run` is a symlink to `/run`. Users that install ksmbd-tools from GitHub will have to set `--with-rundir` or `-Drundir` (or `--runstatedir` if available) to `/run` (or some other `tmpfs`). This is similar to the situation with `--sysconfdir`.  If `--runstatedir` is available in autoconf, `/usr/share/config.site` can be used to change the default much like with `--sysconfdir`.

> > Is ksmbd-tools: derive subauth filename from config filename a good idea?
> 
> I could just not find where subauth file is located before. If this file is located in /var/ or /tmp or the other, It can be removed. The subauth value had to be stored in persistent storage as it should always remain the same. In other words, it should not be changed every time ksmbd.mountd is run, it should be created only on the first run. Hm.. I have no idea why subauth is changed with config filename. ksmbd.mountd cannot be multiply run on the same server as per config filename.

Currently, if the config file is `$HOME/test.conf`, the subauth file is `$HOME/ksmbd.subauth`. I then assumed that the subauth values should be tied to the server configuration. Why isn't it `SYSCONFDIR /ksmbd.subauth`?

> @atheik The best way is to find a way to keep a unique subauth value without creating a subauth file. How about using the checksum of the hostname?

Okay. Does the randomness of the subauth values matter? Or does it only matter that they are unique?

**Comment by namjaejeon** [comment]
>  If --runstatedir is not available, it is $(prefix)/$(localstatedir)/run.

This is default patch "/usr/local/var/run/ksmbd.lock" in my environment. but ksmbd.mountd doesn't launch without --with-rundir option. Because there is no /usr/local/var/run directory.
As we did smb.conf.example, Should we make ksmbd-tools creating default path(/usr/local/var/run) ?

> Why isn't it SYSCONFDIR /ksmbd.subauth?

Ah, Using sysconfidir is introduced recently by you. we can use SYSCONFDIR for ksmbd.subauth. Is there any reason to rename ksmbd.subauth to smb.subauth ? It doesn't matter:)

> Does the randomness of the subauth values matter? Or does it only matter that they are unique?

randomness is not important. We need unique values for this. As you see, 3 unique integer values are needed.

**Comment by atheik** [comment]
@namjaejeon,

> > If --runstatedir is not available, it is (prefix)/(localstatedir)/run.
> 
> This is default patch "/usr/local/var/run/ksmbd.lock" in my environment. but ksmbd.mountd doesn't launch without --with-rundir option. Because there is no /usr/local/var/run directory. As we did smb.conf.example, Should we make ksmbd-tools creating default path(/usr/local/var/run) ?

No, the `install` target cannot create the directory and make sure that its underlying filesystem is `tmpfs`. That's the responsibility of the person running `configure`.
> > Why isn't it SYSCONFDIR /ksmbd.subauth?
> 
> Ah, Using sysconfidir is introduced recently by you. we can use SYSCONFDIR for ksmbd.subauth.

Even before the changes I made, it could have been `/etc/ksmbd/ksmbd.subauth` by parsing the path from `PATH_SMBCONF`. Instead, currently, it is parsed from the run-time path of the config file.

> Is there any reason to rename ksmbd.subauth to smb.subauth ? It doesn't matter:)

I don't understand. `smb.subauth` would have been the name of the subauth file when the config file is `smb.conf`. Likewise, `test.conf` would have resulted in `test.subauth`. You already clarified that the subauth filename should not be derived from the config filename. There is then no need to change the name of `ksmbd.subauth`.

> > Does the randomness of the subauth values matter? Or does it only matter that they are unique?
> 
> randomness is not important. We need unique values for this. As you see, 3 unique integer values are needed.

For this PR, would you prefer `SYSCONFDIR /ksmbd/ksmbd.subauth` or getting rid of the subauth file? I can make the changes for either.

**Comment by namjaejeon** [comment]
> No, the install target should not create the directory and it cannot make sure that its underlying filesystem is tmpfs. That's the responsibility of the person running configure.

I haven't seen any source that doesn't work when building the default ./configure. This is what makes the current ksmbd-tools so. The default rundir path should be available on most Linux systems. If not /tmp, /run or /var/run should be the default rundir.

> For this PR, would you prefer SYSCONFDIR /ksmbd/ksmbd.subauth or getting rid of the subauth file? I can make the changes for either.

For now, Let's use SYSCONFDIR for ksmbd.subauth.

**Comment by atheik** [comment]
> > No, the install target should not create the directory and it cannot make sure that its underlying filesystem is tmpfs. That's the responsibility of the person running configure.
> 
> I haven't seen any source that doesn't work when building the default ./configure. This is what makes the current ksmbd-tools so. The default rundir path should be available on most Linux systems. If not /tmp, /run or /var/run should be the default rundir.

`$(prefix)/$(localstatedir)/run` is the correct `--with-rundir` default for the build system. It is the same default as `--runstatedir`. On my system it resolves to `/usr/local/var/run` (autoconf) and `/var/local/run` (meson) which are both standard paths (search for exact matches on Google for examples). `/tmp`, `/run`, and `/var/run` are not correct defaults for the build system. Distributions adapt to the build system and not the other way around. Please look into this some further.
> > For this PR, would you prefer SYSCONFDIR /ksmbd/ksmbd.subauth or getting rid of the subauth file? I can make the changes for either.
> 
> For now, Let's use SYSCONFDIR for ksmbd.subauth.

Sure.

**Comment by kernel-dev-ko** [comment]
@atheik Thanks for updating. Let me check it.

**Comment by namjaejeon** [comment]
Applied, Thanks for your work!

**Pull request closed without merging**
