### PR TITLE
Fix maximum password length when prompting

### PR DESCRIPTION
**Pull request by atheik**
ksmbd-tools: fix maximum password length when prompting
ksmbd-tools: fix maximum password length detection when prompting

Signed-off-by: atheik \<atteh.mailbox@gmail.com>

### CODE REVIEW

**Comment by atheik** [comment]
When using the `password` option of `ksmbd.adduser`, there is no check that it is less than the maximum password length. This is a bug, right?

**Comment by namjaejeon** [comment]
@atheik Yes! Thanks for your patch, I will check it.

**Comment by namjaejeon** [comment]
Applied, Thanks for your work!

**Comment by atheik** [comment]
@namjaejeon, looks like you forgot to set the author in commit c65c5f4. Also, this leading newline should have been removed: https://github.com/cifsd-team/ksmbd-tools/blob/c65c5f4/adduser/user_admin.c#L121.

**Comment by namjaejeon** [comment]
@atheik Oops, my mistake. Sorry for that:) This patch was conflict with other patch, So I have updated it.. Anyway, FIXED it.

**Pull request closed without merging**
