### PR TITLE
Unify all programs into a single binary "ksmbdctl"

### PR DESCRIPTION
**Pull request by ematsumiya**
[rebased to cifsd-team/ksmbd-tools master]
[!!! not all commits are individually buildable !!!]

--

This PR unifies all existing programs
(ksmbd.{_adduser,addshare,control,mountd_}) into a single `ksmbdctl' binary.

The intention is to make it more like other modern tools (e.g. git,
nvme, virsh, etc) which have more clear user interface, readable
commands, and also makes it easier to script.

Example commands:
```
# ksmbdctl share add myshare -o "guest ok=yes, writable=yes, path=/mnt/data"
# ksmbdctl user add myuser
# ksmbdctl user add -i $HOME/mysmb.conf anotheruser
# ksmbdctl daemon start
```

Besides adding a new "share list" command, any previously working
functionality shouldn't be affected.

Basic testing was done manually.

TODO:
- run more complex tests in more complext environments
- implement tests (for each command and subcommand)
- create an abstract command interface, to make it easier to add/modify
  the commands
- find and fix obvious bugs I missed

Signed-off-by: Enzo Matsumiya <ematsumiya@suse.de>

### CODE REVIEW

**Comment by namjaejeon** [comment]
@ematsumiya Thanks for your patch! And I found that there is build errors on auto-build test.
Could you please check that ? https://github.com/cifsd-team/ksmbd-tools/pull/265/checks?check_run_id=7457313838

**Comment by atheik** [comment]
@ematsumiya, I gave the commits a quick look. When you rebase your changes to `master`, you must also make sure that the changes made are still relevant. In this case, please start from commit 9ad8231 (or older if you remember where). Use `git mv` when possible e.g. move `share/addshare.c` to `share/share.c`. Commit title prefix should be `ksmbd-tools:`. Leave commit c2dcfb8 out. In message to commit 3b2f39e, `,` is not an option separator and `-i` is not an option accepted by `ksmbdctl user add`. When making changes to the autotools build, remember to do `make distcheck` also to catch errors.

I'll add here that I don't understand why ksmbd-tools needs a rewrite like this.

**Comment by ematsumiya** [comment]
> @ematsumiya, I gave the commits a quick look. When you rebase your changes to `master`, you must also make sure that the changes made are still relevant. In this case, please start from commit [9ad8231](https://github.com/cifsd-team/ksmbd-tools/commit/9ad8231473820354187b99f991cd869c5be356f0) (or older if you remember where). Use `git mv` when possible e.g. move `share/addshare.c` to `share/share.c`. Commit title prefix should be `ksmbd-tools:`. Leave commit [c2dcfb8](https://github.com/cifsd-team/ksmbd-tools/commit/c2dcfb85d8ec0baaa3218e8edd44dfb40e149dac) out. In message to commit [3b2f39e](https://github.com/cifsd-team/ksmbd-tools/commit/3b2f39e45190643539da3fa9c044d54868dc05c0), `,` is not an option separator and `-i` is not an option accepted by `ksmbdctl user add`. When making changes to the autotools build, remember to do `make distcheck` also to catch errors.

Thank you very much for your feedback! I'll try to work on those  this week (I have 2 days off though, so it's possible it might get delayed yet again).

> I'll add here that I don't understand why ksmbd-tools needs a rewrite like this.

I tried elaborating on the "why" here: https://lore.kernel.org/all/20211201165728.r3jvaan2hw5icfvp@cyberdelia/
Please let me know why do you think this wouldn't be an improvement.

**Comment by atheik** [comment]
@ematsumiya,

> > I'll add here that I don't understand why ksmbd-tools needs a rewrite like this.
> 
> I tried elaborating on the "why" here: https://lore.kernel.org/all/20211201165728.r3jvaan2hw5icfvp@cyberdelia/ 

Thank for the link to the discussion. I now understand your motivation better.
> Please let me know why do you think this wouldn't be an improvement.

The motivation behind your changes now makes more sense to me. 
I would prefer separate utilities, but don't worry, my opinion on this doesn't hold any weight.

This should fix the `make distcheck` errors:
```diff
diff --git a/Makefile.am b/Makefile.am
index abbdee5..0c68aea 100644
--- a/Makefile.am
+++ b/Makefile.am
@@ -3,7 +3,7 @@
 ACLOCAL_AMFLAGS = -I m4
 
 SUBDIRS = lib
-AM_CFLAGS = -DSYSCONFDIR='"${sysconfdir}"' -Iinclude $(GLIB_CFLAGS) \
+AM_CFLAGS = -DSYSCONFDIR='"${sysconfdir}"' -I$(top_srcdir)/include $(GLIB_CFLAGS) \
 	    $(LIBNL_CFLAGS) -fno-common
 LIBS = $(GLIB_LIBS) $(LIBNL_LIBS) $(LIBKRB5_LIBS)
 ksmbdctl_LDADD = lib/libksmbdtools.a
@@ -15,7 +15,7 @@ user_SOURCES = user/md4_hash.c user/user_admin.c user/user.c user/md4_hash.h \
 	       user/user_admin.h
 daemon_SOURCES = daemon/worker.c daemon/ipc.c daemon/rpc.c daemon/rpc_srvsvc.c \
 		 daemon/rpc_wkssvc.c daemon/daemon.c daemon/smbacl.c \
-		 daemon/rpc_samr.c daemon/rpc_lsarpc.c
+		 daemon/rpc_samr.c daemon/rpc_lsarpc.c daemon/daemon.h
 
 ksmbdctl_SOURCES = $(share_SOURCES) $(user_SOURCES) $(daemon_SOURCES) \
 		   ksmbdctl.c

```

**Comment by ematsumiya** [comment]
@atheik I've force pushed my branch with the fixes for the errors you identified, please let me know if I missed something.

**Comment by atheik** [comment]
@ematsumiya,

> @atheik I've force pushed my branch with the fixes for the errors you identified, please let me know if I missed something.

The argument is missing for `%s` :
https://github.com/cifsd-team/ksmbd-tools/blob/6ae4dae/user/user.c#L178
https://app.travis-ci.com/github/cifsd-team/ksmbd-tools/jobs/577592097#L607

After that you have to rebase your changes to `master` by going over the changes starting from at least commit 9ad8231.
For example, this PR doesn't have the changes made in commits 9ad8231, 62a9579, and 7cfd1ad:
https://github.com/cifsd-team/ksmbd-tools/blob/6ae4dae/share/share.c#L63-L84

**Comment by ematsumiya** [comment]
@atheik force pushed again with those fixes (based on commit 4608cd4, origin/master now). Let's see what did I miss now.

btw thanks a lot for your reviewing! I'm in between several tasks at once, so I'm getting a bit lost lately.

**Comment by dmulder** [comment]
`ksmbdctl daemon shutdown`? I would expect `ksmbdctl daemon stop`

**Comment by atheik** [comment]
@ematsumiya,

> @atheik force pushed again with those fixes (based on commit [4608cd4](https://github.com/cifsd-team/ksmbd-tools/commit/4608cd4d68853967b565ac320936ea5c31d3ba90), origin/master now). Let's see what did I miss now.
> 
> btw thanks a lot for your reviewing! I'm in between several tasks at once, so I'm getting a bit lost lately.

The exact same problem persists. Go over the changes starting from at least commit https://github.com/cifsd-team/ksmbd-tools/commit/9ad8231473820354187b99f991cd869c5be356f0.
For example, this PR still doesn't have the changes made in commits https://github.com/cifsd-team/ksmbd-tools/commit/9ad8231473820354187b99f991cd869c5be356f0, https://github.com/cifsd-team/ksmbd-tools/commit/62a957944c8187a9dbbed9fb4f9bf5f97ef5c33d, and https://github.com/cifsd-team/ksmbd-tools/commit/7cfd1ad771b58e2d0fbaca319e411e861a2fd3d1:
https://github.com/cifsd-team/ksmbd-tools/blob/f416b37/share/share.c#L41-L62
Please, compare your `sanity_check_share_name_simple()` with the one in `master` to see what I mean.
It really would help if you renamed `addshare/addshare.c` to `share/share.c` in a way that its history is preserved.

Please squash changes in f416b37 to one of the preceding commits in your PR.
It would help when the initial review is made.

Why did you comment out `ExecReload` in the unit file template? Take a look at commit f12f98f.

**Comment by namjaejeon** [comment]
@ematsumiya I understand your current situation. No rush. This patch-set has been pending for quite long time, and in the meantime, many patches have been updated to ksmbd-tools, and it seems that there are many conflicts. I think that you need to rebase ksmbd-tools and fix conflicts...

**Comment by namjaejeon** [comment]
@ematsumiya One more, If possible, I hope that you add manpages in this PR.

**Comment by namjaejeon** [comment]
@dmulder Ah, Long time long see since sambaXP 2019:) Is there a big difference between "shutdown" and "stop"? Isn't it usually said to shut down the server?

**Comment by ematsumiya** [comment]
> @ematsumiya I understand your current situation. No rush. This patch-set has been pending for quite long time, and in the meantime, many patches have been updated to ksmbd-tools, and it seems that there are many conflicts. I think that you need to rebase ksmbd-tools and fix conflicts...

Yeah, doing that right now :)

> @ematsumiya One more, If possible, I hope that you add manpages in this PR.

Ok, queued on my TODO.

> @dmulder Ah, Long time long see since sambaXP 2019:) Is there a big difference between "shutdown" and "stop"? Isn't it usually said to shut down the server?

I have to say I agree with David here, and have been using "stop" in my new branch. IMO "shutdown" is associated to "power off", and in this case, where we "start" the daemon, "stop" is much more coherent.

**Comment by ematsumiya** [comment]
I'm closing this PR as my changes were beyond broken when rebased. I'll rework on them and open a new PR when I'm done with at least some basic testing. Thanks everyone for the feedback, I hope you get to review my next submission.

**Comment by dmulder** [comment]
> @dmulder Ah, Long time long see since sambaXP 2019:) Is there a big difference between "shutdown" and "stop"? Isn't it usually said to shut down the server?

As Enzo mentioned, 'shutdown' generally means to turn off the hardware, whereas 'stop' is associated with killing the process. I only mentioned because I keep mistakenly using 'stop' instead of 'shutdown', because it is the term I would expect. Consider the systemctl command from systemd, it uses start/stop/reload/restart.

**Comment by sergey-senozhatsky** [comment]
So I don't remember who came up with 'shutdown", was it Namjae or me, but I never looked at "shutdown" as H/W specific term. E.g. "graceful service shutdown" like go's http server method Shutdown https://pkg.go.dev/net/http#Server.Shutdown , or, again, http shutdown https://www.npmjs.com/package/http-shutdown or postresql shutdown https://www.postgresql.org/docs/current/server-shutdown.html and so on.

**Comment by atheik** [comment]
@dmulder, @ematsumiya,
The term `shutdown` is also used in`smbcontrol` of Samba. The term isn't really associated with hardware. `start`, `stop`, `reload`, and `restart` in `systemctl` are actions done to a *service*, so the comparison isn't apt.

**Pull request closed without merging**
