### PR TITLE
ksmbd-tools: fix memory leak in rpc

### PR DESCRIPTION
**Pull request by aospan**
Steps to reproduce:
 * map network drive from Windows
 * select file->properties
 * observe ksmbd.mountd process growing

Signed-off-by: Abylay Ospan <aospan@netup.ru>

### CODE REVIEW

**Comment by aospan** [comment]
This was an experimental run of ksmbd under Android. I'll try to prepare more information later.
Also, we can use this as a reference:
https://github.com/GNOME/glib/blob/32b4c53295987143caa04361d5eb730b55774c54/glib/gconvert.c#L347

and this:
https://github.com/GNOME/glib/blob/32b4c53295987143caa04361d5eb730b55774c54/glib/gconvert.c#L411

as you can see, for the null-terminated strings, we shouldn't do "+ 1", so the patch is actually valid but probably the description should be changed (change memleak claim to g_convert_with_iconv args description?).
Thanks!

**Comment by ptpt52** [comment]
@namjaejeon @aospan  what about this PR now?

**Comment by namjaejeon** [comment]
Note that there is a problem that NetShareEnum response broken when this patch is applied.
So share list up doesn't work through windows client.

**Comment by namjaejeon** [comment]
No response for long time. Once close this PR. Please reopen it if you want.

**Pull request closed without merging**
