### PR TITLE
ksmbd-tools: set netlink socket's receive buffer size to 1 MiB

### PR DESCRIPTION
**Pull request by database64128**
Fixes https://github.com/cifsd-team/ksmbd-tools/issues/235.

### CODE REVIEW

**Comment by namjaejeon** [comment]
@database64128 Really thanks for your fix! Could you please add patch description and signed-off-by tag in patch ? You can refer other commits in ksmbd-tools git. BTW, Do you know what maximum buffer size is set by default in netlink ?

**Comment by database64128** [comment]
@namjaejeon Please see the updated commit description.

**Comment by namjaejeon** [comment]
@database64128 As you see the below code, ipc message allocation size will be almost 8MB. It is too big for embedded devices like openWRT and dd-wrt. How many shares do you declare in smb.conf ?
```
                resp_msg = ipc_msg_alloc(KSMBD_IPC_MAX_MESSAGE_SIZE -
                                sizeof(struct ksmbd_rpc_command));
```

**Comment by database64128** [comment]
> How many shares do you declare in smb.conf ?

I have 5 shares declared in `smb.conf`.

> It is too big for embedded devices like openWRT and dd-wrt.

What do you think a reasonable size would be for these devices?

**Comment by namjaejeon** [comment]
> What do you think a reasonable size would be for these devices?

Hm.. Don't know. As I know, They are having too small RAM. So they have been setting read/write size to 64KB from default 4MB of ksmbd. I understood that we should increase ipc message allocation size. but Why 8MB... ?
Can you reproduce this issue easily ? because I can not reproduce it on my setup.

**Comment by database64128** [comment]
> but Why 8MB... ?

Because that's what NetworkManager and systemd-networkd went with. But I think we can get away with a lower value. Maybe something like 1MiB?

> Can you reproduce this issue easily ? because I can not reproduce it on my setup.

I could not reproduce this locally either, but the crash used to happen on a daily basis on my home server, which was super annoying and required manual restarts of the ksmbd userspace service. After I applied this patch a week ago, it hasn't happened ever since.

**Comment by namjaejeon** [comment]
> Because that's what NetworkManager and systemd-networkd went with. But I think we can get away with a lower value. Maybe something like 1MiB?

Yes, But we will increase size if 1MB is not sufficient to fix this issue. This is mainline, We don't fix some issue without finding root-cause.

> I could not reproduce this locally either, but the crash used to happen on a daily basis on my home server, which was super annoying and required manual restarts of the ksmbd userspace service. After I applied this patch a week ago, it hasn't happened ever since.

Thanks for your check! It is good hint to find root-cause. We have known ipc allocation size is related to this issue  by this. @consp Can you help fixing this issue ? Because you are able to reproduce this issue.

```
ksmbd: [ksmbd-worker/4178571]: ERROR: Recv() error Out of memory [-5]
```

**Comment by database64128** [comment]
> This is mainline, We don't fix some issue without finding root-cause.

I think the root cause is quite obvious here: The size of netlink messages received may exceed the 32k default buffer size. As I mentioned in the commit message:

> A netlink socket's default buffer size is 32KiB. When a message exceeds
the socket buffer size, the recvmsg(2) call returns -ENOBUFS, which is
then translated to the Out of memory error above by libnl.

So it's just a matter of what buffer size we want to change to. If you think we can settle with 1MiB, I can update the patch to 1MiB.

**Comment by database64128** [comment]
By "I could not reproduce this locally", I mean I do not understand the internals of the SMB protocol and ksmbd enough to be able to do any meaningful minimal reproduction. But I am familiar with the socket interface and networking syscalls, and this patch is a very straightforward fix with regard to the error returned by `recvmsg(2)`.

**Comment by namjaejeon** [comment]
> So it's just a matter of what buffer size we want to change to. If you think we can settle with 1MiB, I can update the patch to 1MiB.

I am wondering why payload size of netlink exceed default 32KB. and If it exceeds 32KB, it must be split into several pieces and send multiple times. I can't imagine what kind of data is over 32KB. and 1MB size buffer is still large for embedded device.

**Comment by namjaejeon** [comment]
> By "I could not reproduce this locally", I mean I do not understand the internals of the SMB protocol and ksmbd enough to be able to do any meaningful minimal reproduction. But I am familiar with the socket interface and networking syscalls, and this patch is a very straightforward fix with regard to the error returned by recvmsg(2).

I know it can fix current issue. However, I am scaring this patch cause other issues on embedded device. If I get more information on reproduction, We can reach for more right solution.

**Comment by namjaejeon** [comment]
@database64128 What kernel version do you use ?

**Comment by database64128** [comment]
I experience this issue on all kernel versions from 5.15 to 5.19 with the upstreamed ksmbd module.

**Comment by namjaejeon** [comment]
@database64128 netlink kernel max buffer size seems be 32KB. If < 4.9 kernel, it is limited to 16KB.
https://www.spinics.net/lists/netdev/msg431592.html

I guess that your issue can be fixed when just increasing buffer size to 32KB. Can you check your issue is fixed with the below change ?
```
diff --git a/include/ipc.h b/include/ipc.h
index 115d510..b0d1381 100644
--- a/include/ipc.h
+++ b/include/ipc.h
@@ -12,7 +12,7 @@
  * Older [prior to 4.9] kernels had max NL recv msg size of 16k.
  * It has been bumped to 32K later on.
  */
-#define KSMBD_IPC_MAX_MESSAGE_SIZE     (16 * 1024)
+#define KSMBD_IPC_MAX_MESSAGE_SIZE     (32 * 1024)
 
 struct ksmbd_ipc_msg {
        unsigned int    type;
```

**Comment by database64128** [comment]
> Can you check your issue is fixed with the below change

Unlikely. This change only raises the size of the buffer passed to `recvmsg(2)`, not the socket receive buffer size. If this was the problem, the error would have been `-EMSGSIZE`, not `-ENOBUFS`.

**Comment by namjaejeon** [comment]
@database64128 Please ignore this change. I need to think more.

**Comment by database64128** [comment]
> netlink kernel max buffer size seems be 32KB. If < 4.9 kernel, it is limited to 16KB.
https://www.spinics.net/lists/netdev/msg431592.html

Thanks for the info! It made me realize we may have been looking at the wrong direction. It's not any individual netlink message that won't fit in the socket buffer. To my understanding, the size of a netlink message is still capped to 32K in the latest kernel. What's actually going on is, there are so many messages being queued up in the receive buffer, that the default buffer size (208K) is not enough.

`systemd-networkd` has a bug report with more details: systemd/systemd#14417. It also prompted a further increase of receive buffer size to 128M: systemd/systemd#14434. Also according to this PR:

> Is this memory permanently reserved, or on demand?

> It's a limit, not more. i.e. when nothing is in the buffer no memory is allocated for it. And if there's little in the buffer only little is allocated.

Therefore, this PR can be simplified to a simple `nl_socket_set_buffer_size` call to raise the socket buffer size. `KSMBD_IPC_MAX_MESSAGE_SIZE` won't even need to be changed.

**Comment by namjaejeon** [comment]
@database64128 Looks good. nl_socket_set_buffer_size means doesn't Immediately allocate 1MB memory. right? It is just maximum size of buffers in queue ? And Can you confirm that this patch fix your ENOBUFS issue on your target ?

**Comment by database64128** [comment]
The updated patch has been running on my home server for 2 days, and everything is working fine. I think this patch is ready.

**Comment by namjaejeon** [comment]
@database64128 Nice! I will apply this patch today after checking memory usage. Thanks for your the patch!

**Comment by namjaejeon** [comment]
Applied, Thanks for your work! If you find same issue later, Let me know it.

**Comment by mmakassikis** [comment]
A bit late to the party, but I wonder if there isn't another problem hiding.

> What's actually going on is, there are so many messages being queued up in the receive buffer, that the default buffer size (208K) is not enough.

That's my understanding as well: the kernel tries to write a message in the socket buffer, but there's not enough room so it throws a ENOBUFS error. Why does that happen though ? An obvious reason is that the message is indeed too large (perhaps a new RPC command with a larger payload ? IIRC you saw this error with Win11 clients).

Another reason could be that ksmbd.mountd is not processing messages fast enough, so there's enough time for data to accumulate between each call to recv().

Do you regularly see the error without resizing the receive buffer ? If so, is there any chance you could add some debug code in either `ipc_process_event` or `handle_generic_event` to measure how much time is spent processing each message, as well as the size of each netlink message ?

**Comment by database64128** [comment]
> An obvious reason is that the message is indeed too large (perhaps a new RPC command with a larger payload ? IIRC you saw this error with Win11 clients).

The following error does show up in the logs from time to time, with or without the patch:

```
[ksmbd-worker/1897143]: ERROR: SRVSVC: unsupported INVOKE method 21
```

> Do you regularly see the error without resizing the receive buffer ?

Without resizing the receive buffer the error happens almost on a daily basis.

> If so, is there any chance you could add some debug code in either `ipc_process_event` or `handle_generic_event` to measure how much time is spent processing each message, as well as the size of each netlink message ?

This issue only occurs on my home server, not my secondary devices (also running ksmbd). I'd very much prefer not to run experiments on my home server. Maybe someone else with the same issue can step in and do some experiments?

**Comment by mmakassikis** [comment]
Do you use the same type of clients on the home server and secondary devices ?

I can try to setup a Win11 VM and do some tests if that helps trigger the error.

**Comment by database64128** [comment]
> Do you use the same type of clients on the home server and secondary devices ?

Not exactly. The home server serves a variety of devices, whereas my secondary devices are only occasionally used for testing or simple file transfers.

It seems to be very difficult, if not nearly impossible, to deliberately trigger the issue. But I'm confident that in my case the issue was triggered by at least one of the Win11 clients.

**Comment by namjaejeon** [comment]
@mmakassikis 

The reason I take this problem seriously is that other users have had the same problem.

See:
https://github.com/cifsd-team/ksmbd/issues/543#issuecomment-1228132771

> I can try to setup a Win11 VM and do some tests if that helps trigger the error.

Really thanks for your help! It will be great if you find root-cause.

**Comment by namjaejeon** [comment]
@mmakassikis Any news ? I will release ksmbd-tools included this change on this weekend. Is there any concern about this ?

**Pull request closed without merging**
