### PR TITLE
add a note on prebuilt binaries

### PR DESCRIPTION
**Pull request by alexmyczko**

### CODE REVIEW

**Comment by namjaejeon** [comment]
You need to add a item for this in Table of Contents.

Applied, Thanks for your patch.

**Comment by namjaejeon** [comment]
@atheik Let me know your opinion. I can just add a item for this in Table of Contents ?

**Comment by atheik** [comment]
@namjaejeon, @alexmyczko,

Sorry, I missed this PR. I am not familiar with the Repology project. Looks like the link leads to a list of downstream packagers of ksmbd-tools. So, merging this is a matter of deciding to trust Repology. Since you trust it and merged this, then adding the section to Table of Contents is definitely right.

**Comment by namjaejeon** [comment]
@atheik OK.

**Comment by namjaejeon** [comment]
Done. Thanks for your patch!

**Pull request closed without merging**
