### PR TITLE
ksmbd-tools: build utilities as a single binary

### PR DESCRIPTION
**Pull request by atheik**
Rather than have four different binaries, i.e. ksmbd.addshare, ksmbd.adduser, ksmbd.control, and ksmbd.mountd, each one including its own libksmbdtools.a copy, build them instead as a single binary. This resulting ksmbd.tools acts like BusyBox in that its behavior depends on the name by which it is called. Then, each utility is made into a symlink to it, meaning that users keep using the utilities as usual. ksmbd.tools itself is installed to libexecdir as it is not something the user should run.

Instead of libksmbdtools.a, each utility becomes its own static library, i.e. libaddshare.a, libadduser.a, libcontrol.a, libmountd.a, which are all linked to the single binary. Note that the single binary approach is also beneficial when statically linking to any of the external dependencies, e.g. GLib, as it greatly reduces the overall binary size when there is overlap in copies otherwise made separately for multiple utilities.

Due to install_symlink(), minimum meson version is bumped to 0.61.5, meaning that it has to be installed using `pip' in Travis, since no Ubuntu release currently packages that version or newer. However, bump to Ubuntu Jammy anyways, just for the sake of building against newer versions of ksmbd-tools' dependencies.

Signed-off-by: Atte Heikkilä \<atteh.mailbox@gmail.com>

### CODE REVIEW

**Comment by atheik** [comment]
I can't reproduce the meson build fail locally. I think it happens because meson 0.61.2 does not have this fix: https://github.com/mesonbuild/meson/commit/b0d300e788571f48e95d6e673c6f94e54d1dd355. So, it seems that the minimum meson version has to be bumped to 0.63.0, which then would have to be installed using `pip` in Travis.

**Comment by atheik** [comment]
> I think it happens because meson 0.61.2 does not have this fix: [mesonbuild/meson@b0d300e](https://github.com/mesonbuild/meson/commit/b0d300e788571f48e95d6e673c6f94e54d1dd355). So, it seems that the minimum meson version has to be bumped to 0.63.0, which then would have to be installed using `pip` in Travis.

That was it.

**Comment by atheik** [comment]
Here is a build demonstrating significant utility size reduction when statically linking GLib:

Meson configure for building static GLib 2.74.0: `-Dbuildtype=minsize` `-Ddefault_library=static`  
`-Dstrip=true` `-Db_lto=true` `-Dglib_assert=false` `-Dglib_checks=false` `-Dglib_debug=disabled`  
`-Dnls=disabled` `-Dselinux=disabled` `-Dtests=false`

Patch for configuring ksmbd-tools with static GLib 2.74.0:
```patch
diff --git a/meson.build b/meson.build
index 14f9375..c3efcf6 100644
--- a/meson.build
+++ b/meson.build
@@ -21,6 +21,7 @@ include_dirs = include_directories(
 glib_dep = dependency(
   'glib-2.0',
   version: '>= 2.40',
+  static: true,
 )
 libnl_dep = dependency(
   'libnl-genl-3.0',

```

Meson configure for building ksmbd-tools with static GLib 2.74.0: `-Dbuildtype=minsize` `-Dstrip=true`  
`-Db_lto=true` `-Drundir=/run`

Old utility sizes (cifsd-team@c97b53f):
```
-rwxr-xr-x 1 root root 780K Oct 13 00:09  /usr/local/sbin/ksmbd.addshare
-rwxr-xr-x 1 root root 796K Oct 13 00:09  /usr/local/sbin/ksmbd.adduser
-rwxr-xr-x 1 root root 772K Oct 13 00:09  /usr/local/sbin/ksmbd.control
-rwxr-xr-x 1 root root 841K Oct 13 00:09  /usr/local/sbin/ksmbd.mountd

```

New utility sizes (atheik@c4ed8fc):
```
-rwxr-xr-x 1 root root 861K Oct 13 00:12 /usr/local/libexec/ksmbd.tools
lrwxrwxrwx 1 root root   30 Oct 13 00:12 /usr/local/sbin/ksmbd.addshare -> /usr/local/libexec/ksmbd.tools
lrwxrwxrwx 1 root root   30 Oct 13 00:12 /usr/local/sbin/ksmbd.adduser -> /usr/local/libexec/ksmbd.tools
lrwxrwxrwx 1 root root   30 Oct 13 00:12 /usr/local/sbin/ksmbd.control -> /usr/local/libexec/ksmbd.tools
lrwxrwxrwx 1 root root   30 Oct 13 00:12 /usr/local/sbin/ksmbd.mountd -> /usr/local/libexec/ksmbd.tools

```

**Comment by eli-schwartz** [comment]
> I can't reproduce the meson build fail locally. I think it happens because meson 0.61.2 does not have this fix: [mesonbuild/meson@b0d300e](https://github.com/mesonbuild/meson/commit/b0d300e788571f48e95d6e673c6f94e54d1dd355). So, it seems that the minimum meson version has to be bumped to 0.63.0, which then would have to be installed using `pip` in Travis.

Note that this was backported to Meson's LTS branch and included in the 0.61.5 tag, and also backported to 0.62.1 (not an LTS).

So at least it is present in *all* versions >=0.62.1, and TBH you could assume that anyone using 0.62.x is using at least point release .1, that's what point releases are for.

Allowing the LTS release is mostly important for systems that cling to Python 3.6, which is EOL anyway, so it's debatable whether that actually matters...

> Patch for configuring ksmbd-tools with static GLib 2.74.0:

BTW if you are going to be building with Meson 0.63.0 anyway, there is https://mesonbuild.com/Release-notes-for-0-63-0.html#new-prefer_static-builtin-option

**Comment by atheik** [comment]
@namjaejeon, @neheb,

> @neheb Could you please check if there is build issue when applying this patch to ksmbd-tools in openWRT ?

The packaging would have to be changed in OpenWRT. Looks like they split ksmbd-tools into [ksmbd-server](https://openwrt.org/packages/pkgdata/ksmbd-server) (mountd) and [ksmbd-utils](https://openwrt.org/packages/pkgdata/ksmbd-utils) (addshare, adduser).

**Comment by neheb** [comment]
I'll test when I can. ksmb-utils can go. Simpler to have one package.

**Comment by atheik** [comment]
@namjaejeon,

As per Eli's suggestion, I lowered the minimum meson version from 0.63.0 to 0.62.1 and force-pushed.

**Comment by neheb** [comment]
Should lower to 0.61.5. That’s what OpenWrt uses.

**Comment by eli-schwartz** [comment]
> Allowing the LTS release is mostly important for systems that cling to Python 3.6, which is EOL anyway, so it's debatable whether that actually matters...

Ah, right, I forgot that OpenWrt still supports systems running on Python 3.6.

**Comment by neheb** [comment]
ugh 3.4.6 did not add meson files to the tarball.

@atheik can you make a PR adding meson files to EXTRA_DIST?

**Comment by neheb** [comment]
doesn't work when cross compiling:

```
lrwxrwxrwx. 1 mangix mangix 24 Oct 13 13:07 ksmbd.addshare -> /usr/libexec/ksmbd.tools
lrwxrwxrwx. 1 mangix mangix 24 Oct 13 13:07 ksmbd.adduser -> /usr/libexec/ksmbd.tools
lrwxrwxrwx. 1 mangix mangix 24 Oct 13 13:07 ksmbd.control -> /usr/libexec/ksmbd.tools
lrwxrwxrwx. 1 mangix mangix 24 Oct 13 13:07 ksmbd.mountd -> /usr/libexec/ksmbd.tools
```

**Comment by atheik** [comment]
@neheb,

> Should lower to 0.61.5. That’s what OpenWrt uses.

Okay, I will do that.

> ugh 3.4.6 did not add meson files to the tarball.
> 
> @atheik can you make a PR adding meson files to EXTRA_DIST?

Do they belong in an automake dist tarball? They weren't added there in your PR for meson support.

You can use this tarball created automatically by GitHub:
https://github.com/cifsd-team/ksmbd-tools/archive/3.4.6/ksmbd-tools-3.4.6.tar.gz

I have never seen these automatically created tarballs change checksums.

> doesn't work when cross compiling:
> 
> ```
> lrwxrwxrwx. 1 mangix mangix 24 Oct 13 13:07 ksmbd.addshare -> /usr/libexec/ksmbd.tools
> lrwxrwxrwx. 1 mangix mangix 24 Oct 13 13:07 ksmbd.adduser -> /usr/libexec/ksmbd.tools
> lrwxrwxrwx. 1 mangix mangix 24 Oct 13 13:07 ksmbd.control -> /usr/libexec/ksmbd.tools
> lrwxrwxrwx. 1 mangix mangix 24 Oct 13 13:07 ksmbd.mountd -> /usr/libexec/ksmbd.tools
> ```

Please be more specific. What does not work?

**Comment by neheb** [comment]
OpenWrt's build system uses a prefix of /usr, which results in broken symlinks. I worked around by replacing get_option('prefix') with '..'

**Comment by atheik** [comment]
@neheb,

> OpenWrt's build system uses a prefix of /usr, which results in broken symlinks. I worked around by replacing get_option('prefix') with '..'

Sorry, I still don't understand. What is the location of `ksmbd.tools` in destdir?

**Comment by neheb** [comment]
It's worked around. Don't worry about it. Anyway

3.4.5:
```
-rw-r--r--. 1 mangix mangix 73967 Oct 13 13:42 ksmbd-server_3.4.5-1_mips64_mips64r2.ipk
-rw-r--r--. 1 mangix mangix 41110 Oct 13 13:42 ksmbd-utils_3.4.5-1_mips64_mips64r2.ipk
```

3.4.6:
```
-rw-r--r--. 1 mangix mangix 122459 Oct 13 13:39 ksmbd-server_3.4.6-7_mips64_mips64r2.ipk
-rw-r--r--. 1 mangix mangix  97468 Oct 13 13:41 ksmbd-utils_3.4.6-7_mips64_mips64r2.ipk
```

3.4.6+this PR
```
-rw-r--r--. 1 mangix mangix 130909 Oct 13 13:44 ksmbd-server_3.4.6-1_mips64_mips64r2.ipk
```

I guess there's a small size reduction.

**Comment by atheik** [comment]
@neheb,

> It's worked around. Don't worry about it.

No, please tell me. I want to understand what the build system is doing.
> Anyway
> 
> 3.4.5:
> 
> ```
> -rw-r--r--. 1 mangix mangix 73967 Oct 13 13:42 ksmbd-server_3.4.5-1_mips64_mips64r2.ipk
> -rw-r--r--. 1 mangix mangix 41110 Oct 13 13:42 ksmbd-utils_3.4.5-1_mips64_mips64r2.ipk
> ```
> 
> 3.4.6:
> 
> ```
> -rw-r--r--. 1 mangix mangix 122459 Oct 13 13:39 ksmbd-server_3.4.6-7_mips64_mips64r2.ipk
> -rw-r--r--. 1 mangix mangix  97468 Oct 13 13:41 ksmbd-utils_3.4.6-7_mips64_mips64r2.ipk
> ```
> 
> 3.4.6+this PR
> 
> ```
> -rw-r--r--. 1 mangix mangix 130909 Oct 13 13:44 ksmbd-server_3.4.6-1_mips64_mips64r2.ipk
> ```
> 
> I guess there's a small size reduction.

Did you take into account that `3.4.6+this PR` also has addshare and control? Isn't it the case that `3.4.5` and `3.4.6` only have mountd and adduser?

**Comment by atheik** [comment]
@neheb,

> The files are installed with install -m0755, which is not compatible with dead symlinks and gets rid of them. cp fixes that.
> 
> It creates dead symlinks but on device it should work properly.

Ah, so the OpenWRT build system does not allow creating an `.ipk` package that has symlinks which are dead at the time of package creation? And that is the case because `install -m 755` is used for moving the files to the directory from which the package is created? Instead of replacing `get_option('prefix')` with `..`, i.e. making the symlink relative, why not change `$(INSTALL_BIN)` (or whatever it is) with `$(CP)` in the OpenWRT packaging script? This does not look like a ksmbd-tools bug.

**Comment by atheik** [comment]
@neheb,

> ```
> /home/mangix/devstuff/openwrt/build_dir/target-mips64el_mips64r2_64_musl/ksmbd-tools-3.4.6/ipkg-install/usr/sbin
> ```
> 

This is a bit offtopic, and maybe you just copied the wrong location, but `ksmbd.tools` should not be installed to `/usr/sbin`. 

> > I guess there's a small size reduction.
> 
> Did you take into account that `3.4.6+this PR` also has addshare and control? Isn't it the case that `3.4.5` and `3.4.6` only have mountd and adduser?

Sorry, but did you notice this question of mine? The `3.4.5` and `3.4.6` in your listing do not include `ksmbd.control` and `ksmbd.addshare`, right? Instead, the `3.4.6+this PR` listing does include all utilities.

**Comment by atheik** [comment]
@namjaejeon,

The minimum meson version was further lowered from 0.62.1 to 0.61.5 in order to accommodate OpenWRT. Note that 0.62.0 is now falsely considered a supported meson version.

**Comment by neheb** [comment]
you could write a check for 0.62.0 and error if used.

**Comment by eli-schwartz** [comment]
Remember also that it's only broken if you install using $DESTDIR :)

**Comment by namjaejeon** [comment]
Applied, Thanks for your patch!

**Comment by namjaejeon** [comment]
> can you make a PR adding meson files to EXTRA_DIST?

@neheb Done. Please check it(https://github.com/cifsd-team/ksmbd-tools/commit/d973939949c0f49ab46c8eecec6a4378ecf8ecd7)

**Pull request closed without merging**
