### PR TITLE
Changes related to systemd and config reloading

### PR DESCRIPTION
**Pull request by atheik**
ksmbd-tools: cleanup autotools and meson builds
ksmbd-tools: remove systemd service mode and fix unit file
ksmbd-tools: install systemd unit file when applicable
ksmbd-tools: notify ksmbd of all commands

See https://github.com/cifsd-team/ksmbd-tools/pull/256#issuecomment-1174333299.

Signed-off-by: atheik \<atteh.mailbox@gmail.com>

### CODE REVIEW

**Comment by namjaejeon** [comment]
@sergey-senozhatsky Any opinion about @atheik question ?

**Comment by sergey-senozhatsky** [comment]
I don't understand how the commit c4ff80f works. We did not handle shares reload previously because we don't destroy existing shares sessions on the ksmb side (kernel side). So share configs, in theory, can not be reloaded until kernel has a session open for that share. Or do we force kernel to close all shares sessions now when smb.conf is updated and reloaded on the user-space side?

**Comment by sergey-senozhatsky** [comment]
```I'll add here that I don't understand the extra fork done in the systemd service mode. If it is to prevent acquiring a controlling terminal then surely the extra fork would be just as needed in the regular way of running.```

IIRC it was for controlling terminal. Back in the days we ran only systemd environments so it might be that we miss something for non-systemd cases.

**Comment by atheik** [comment]
I have now tested that the systemd service mode does *not* protect the manager process from acquiring a controlling terminal. You can also test this by applying the following patch to `master` and checking the output of `ps -ef | grep ksmbd`:

```diff
diff --git a/mountd/mountd.c b/mountd/mountd.c
index 2800269..038ce6e 100644
--- a/mountd/mountd.c
+++ b/mountd/mountd.c
@@ -488,6 +488,8 @@ static int manager_process_init(void)
 			pr_err("Daemonization failed\n");
 			goto out;
 		}
+
+		(void) open("/dev/tty22", O_RDWR);
 	} else {
 		/*
 		 * Make ourselves a process group leader; if we are

```

I have updated the related commit message.

**Comment by sergey-senozhatsky** [comment]
> > I don't know how commit [c4ff80f](https://github.com/cifsd-team/ksmbd-tools/commit/c4ff80f1ffd5f9d1f64a76f28e52a28e823b34db) interacts with the kernel side of things, so that is a question for @namjaejeon.
> 
> Can you help me figure out which behavior is actually wrong with the code now?

Well, I'm just curious how does it work. Share configs are cached on the server side. And when new connection arrives we lookup cached share config and only if ksmd does not have cached share config we do user-space IPC request to get the share config. So as long as there is at least one ksmb share session new connections/sessions will use cached (old) share config. Reloading share configs on the user-space does not mean that:
a) we actually use it on ksmb side
b) new connections will use it

So how does it work? Does ksmb invalidate all cached share configs and terminate all sessions forcing users to reconnect and to read new share configuration when user-space daemon reloads config?

**Comment by namjaejeon** [comment]
@sergey-senozhatsky Ah, ksmbd doesn't cache share configs, it always request it to ksmbd.mountd using IPC whenever new connection from client. So when we have applied "ksmbd-tools: notify ksmbd of all commands" in this PR, we can get the following result.

1. add new share.
root@linkinjeon-Precision-Tower-3620:~# sudo ksmbd.addshare --add-share=MyShare --options="
path = /mnt/3
read only = no
"

2. can mount with new share.
root@linkinjeon-Precision-Tower-3620:~# mount -t cifs //10.177.240.90/myshare /mnt/test -ousername=linkinjeon,password=1234,vers=3.11
root@linkinjeon-Precision-Tower-3620:~# sudo umount /mnt/test

3. delete share in conf.
root@linkinjeon-Precision-Tower-3620:~# sudo ksmbd.addshare --del-share=MyShare
[ksmbd.addshare/19869]: INFO: share 'myshare' removed

4. mount failed with deleted share.
root@linkinjeon-Precision-Tower-3620:~# mount -t cifs //10.177.240.90/myshare /mnt/test -ousername=linkinjeon,password=1234,vers=3.11
mount: /mnt/test: bad option; for several filesystems (e.g. nfs, cifs) you might need a /sbin/mount.<type> helper program.

**Comment by namjaejeon** [comment]
@sergey-senozhatsky I would like to get your review from systemd service mode patches in this PR.

**Comment by namjaejeon** [comment]
@sergey-senozhatsky ignore my reply. there is a existing share with connection in ksmbd, it is will be cached.
BTW, Why this patch(https://github.com/cifsd-team/ksmbd-tools/commit/c4ff80f1ffd5f9d1f64a76f28e52a28e823b34db) is a problem ? This patch allow to add new share and new user, not deleting share and user account.

**Comment by sergey-senozhatsky** [comment]
> @sergey-senozhatsky ignore my reply. there is a existing share with connection in ksmbd, it will be cached. BTW, Why this patch([c4ff80f](https://github.com/cifsd-team/ksmbd-tools/commit/c4ff80f1ffd5f9d1f64a76f28e52a28e823b34db)) is a problem ? This patch allow to add new share and new user, not deleting share and user account.

It seems that it removes user-space share configs - usm_remove_all_users().

**Comment by sergey-senozhatsky** [comment]
> @sergey-senozhatsky I would like to get your review from systemd service mode patches in this PR.

Any chance you can give it a try on Tizen board?

**Comment by namjaejeon** [comment]
> It seems that it removes user-space share configs - shm_remove_all_shares() /* edited */

Sorry for making you confusing. I misunderstood that the share is cached on the client. When I have tested it again, ksmbd server always request share config to ksmbd.mountd whenerver new connection. it seems to be calling shm_remove_all_shares to reload.

**Comment by namjaejeon** [comment]
> At least currently ksmbd.mountd doesn't open a terminal device in the manager or worker process (all output goes to syslog) 

I can see print output when running ksmbd.mountd with -n option(nodetach).

**Comment by atheik** [comment]
> > At least currently ksmbd.mountd doesn't open a terminal device in the manager or worker process (all output goes to syslog)
> 
> @atheik I can see print output when running ksmbd.mountd with -n option(nodetach).

@namjaejeon, unintentionally acquiring a controlling terminal is only a problem when daemonizing. `--nodetach` does not daemonize. https://github.com/cifsd-team/ksmbd-tools/blob/e5470dd/mountd/mountd.c#L485-L499

**Comment by atheik** [comment]
@namjaejeon, `pr_logger_init(PR_LOGGER_SYSLOG)` is called when daemonizing, and when not (`--nodetach`), the earlier `pr_logger_init(PR_LOGGER_STDIO)` in `main()` applies.

**Comment by atheik** [comment]
> > @sergey-senozhatsky I would like to get your review from systemd service mode patches in this PR.
> 
> Any chance you can give it a try on Tizen board?

@sergey-senozhatsky, was this comment directed at me? I don't understand what you mean. The reason for the systemd service mode (extra fork) remains unknown since it does not protect the manager process from acquiring a controlling terminal. For it to do that, it would have to be after `setsid()` (which is in `daemon()`).

**Comment by sergey-senozhatsky** [comment]
> > > @sergey-senozhatsky I would like to get your review from systemd service mode patches in this PR.
> > 
> > 
> > Any chance you can give it a try on Tizen board?
> 
> @sergey-senozhatsky, was this comment directed at me? I don't understand what you mean. The reason for the systemd service mode (extra fork) remains unknown

Oh, no, no. I asked @namjaejeon I recall that this fork in systemd mode was needed on Tizen, but I unfortunately don't recall all the details now.

**Comment by sergey-senozhatsky** [comment]
> Sorry for making you confusing. I misunderstood that the share is cached on the client. When I have tested it again, ksmbd server always request share config to ksmbd.mountd whenerver new connection.

I guess because those are not parallel connections. You connect, disconnect (last share config ref-count put frees cached config). But things should be different in this scenario:

1) connect to a share A client A (IPC read share config, cache)
2) update smb.conf reload smb.conf
3) connect to a share A client B (read cached share config)

share A smb.conf changes should not take effect as long as kernel has it cached.

It should be same with deleted share. As long as the kernel keep cached share config value new connections will succeed.
Unless I'm completely wrong.

**Comment by atheik** [comment]
@sergey-senozhatsky, is this what you mean?

```sh
sudo ksmbd.control --shutdown

mkdir -vp $HOME/MyShare $HOME/MyShareMntA $HOME/MyShareMntB

sudo ksmbd.addshare --config=$HOME/test.conf --add-share=MyShare --options="
path = $HOME/MyShare
read only = no
"

sudo ksmbd.adduser --import-users=$HOME/test.db --add-user=MyUser --password=MyPassword

sudo ksmbd.addshare --config=$HOME/test.conf --update-share=MyShare --options="
force user = $USER
force group = $USER
"

sudo ksmbd.mountd --config=$HOME/test.conf --users=$HOME/test.db

sudo mount -o user=MyUser,pass=MyPassword //127.0.0.1/MyShare $HOME/MyShareMntA
sudo touch $HOME/MyShareMntA/file_owner_is_$USER
ls -lah $HOME/MyShare
# total 8.0K
# drwxr-xr-x  2 atte atte 4.0K Jul  8 11:50 .
# drwx------ 23 atte atte 4.0K Jul  8 11:50 ..
# -rwxr--r--  1 atte atte    0 Jul  8 11:50 file_owner_is_atte

sudo ksmbd.addshare --update-share=MyShare --config=$HOME/test.conf --options="
force user = root
force group = root
"

sudo kill -HUP $(cat /tmp/ksmbd.lock)

sudo mount -o user=MyUser,pass=MyPassword //127.0.0.1/MyShare $HOME/MyShareMntB
sudo touch $HOME/MyShareMntB/file_owner_should_be_root
ls -lah $HOME/MyShare
# total 8.0K
# drwxr-xr-x  2 atte atte 4.0K Jul  8 11:51 .
# drwx------ 23 atte atte 4.0K Jul  8 11:50 ..
# -rwxr--r--  1 atte atte    0 Jul  8 11:50 file_owner_is_atte
# -rwxr--r--  1 atte atte    0 Jul  8 11:51 file_owner_should_be_root

# `file_owner_should_be_root' is owned by $USER instead of root
# share update did not apply due to ~/MyShareMntA being mounted

sudo umount $HOME/MyShareMntA $HOME/MyShareMntB

sudo mount -o user=MyUser,pass=MyPassword //127.0.0.1/MyShare $HOME/MyShareMntA
sudo touch $HOME/MyShareMntA/file_owner_is_root
ls -lah $HOME/MyShare
# total 8.0K
# drwxr-xr-x  2 atte atte 4.0K Jul  8 11:57 .
# drwx------ 23 atte atte 4.0K Jul  8 11:50 ..
# -rwxr--r--  1 atte atte    0 Jul  8 11:50 file_owner_is_atte
# -rwxr--r--  1 root root    0 Jul  8 11:57 file_owner_is_root
# -rwxr--r--  1 atte atte    0 Jul  8 11:51 file_owner_should_be_root

# share update applied after all mounts of the share were unmounted
```

So if a share is deleted, it can still be accessed as long as someone has it mounted, right?

**Comment by namjaejeon** [comment]
> sudo mount -o user=MyUser,pass=MyPassword //127.0.0.1/MyShare $HOME/MyShareMntB

@atheik smb client doesn't send tree connect request to ksmbd on second mount. caching share is done in the client, not in the server. When I have tested "ksmbd-tools: notify ksmbd of all commands" patch, it work fine as we expected.

**Comment by namjaejeon** [comment]
@atheik And you should not use the same user account on the second mount to make sure share caching works on the server. please try other user account on second mount.

**Comment by namjaejeon** [comment]
@sergey-senozhatsky @atheik I currently can't use the Tizen board anymore. and this option is not used in Tizen. So we can remove it.

**Comment by atheik** [comment]
@namjaejeon, thanks for the clarification. I am not sure I understand though. This is intended right?

```sh
# following is ran in linux

sudo ksmbd.control --shutdown

mkdir -vp $HOME/MyShare $HOME/MyShareMnt

sudo ksmbd.addshare --config=$HOME/test.conf --add-share=MyShare --options="
path = $HOME/MyShare
read only = no
"

sudo ksmbd.adduser --import-users=$HOME/test.db --add-user=MyUserA --password=MyPassword
sudo ksmbd.adduser --import-users=$HOME/test.db --add-user=MyUserB --password=''

sudo ksmbd.addshare --config=$HOME/test.conf --update-share=MyShare --options="
force user = $USER
force group = $USER
"

sudo ksmbd.mountd --config=$HOME/test.conf --users=$HOME/test.db

sudo mount -o user=MyUserA,pass=MyPassword //127.0.0.1/MyShare $HOME/MyShareMnt
sudo touch $HOME/MyShareMnt/file_owner_is_$USER
ls -lah $HOME/MyShare
# total 8.0K
# drwxr-xr-x  2 atte atte 4.0K Jul  9 19:14 .
# drwx------ 22 atte atte 4.0K Jul  9 19:13 ..
# -rwxr--r--  1 atte atte    0 Jul  9 19:14 file_owner_is_atte

sudo ksmbd.addshare --config=$HOME/test.conf --update-share=MyShare --options="
force user = root
force group = root
"

sudo kill -HUP $(cat /tmp/ksmbd.lock)

networkctl status | grep Address
#          Address: 192.168.1.105 on wlan0

# following is ran in termux on android

touch file
smbclient --user=MyUserB --command="put $HOME/file /file_owner_should_be_root" //192.168.1.105/MyShare

# following is ran in linux

ls -lah $HOME/MyShare
# total 8.0K
# drwxr-xr-x  2 atte atte 4.0K Jul  9 19:15 .
# drwx------ 22 atte atte 4.0K Jul  9 19:13 ..
# -rwxr--r--  1 atte atte    0 Jul  9 19:14 file_owner_is_atte
# -rwxr--r--  1 atte atte    0 Jul  9 19:15 file_owner_should_be_root

# `file_owner_should_be_root' is owned by $USER instead of root
# share update did not apply due to ~/MyShareMnt being mounted

sudo umount $HOME/MyShareMnt

# following is ran in termux on android

touch file
smbclient --user=MyUserB --command="put $HOME/file /file_owner_is_root" //192.168.1.105/MyShare

# following is ran in linux

ls -lah $HOME/MyShare
# total 8.0K
# drwxr-xr-x  2 atte atte 4.0K Jul  9 19:16 .
# drwx------ 22 atte atte 4.0K Jul  9 19:13 ..
# -rwxr--r--  1 atte atte    0 Jul  9 19:14 file_owner_is_atte
# -rwxr--r--  1 root root    0 Jul  9 19:16 file_owner_is_root
# -rwxr--r--  1 atte atte    0 Jul  9 19:15 file_owner_should_be_root

# share update applied after all mounts of the share were unmounted
```

**Comment by atheik** [comment]
@namjaejeon, I updated the `ksmbd-tools: remove systemd service mode and fix unit file` commit so that it removes the outdated and now obsolete `scripts/install.sh`. By the way, `modprobe@.service` was introduced in systemd v245 which was released in 2020-03-06. Is this a problem?

**Comment by namjaejeon** [comment]
> smbclient --user=MyUserB --command="put $HOME/file /file_owner_should_be_root" //192.168.1.105/MyShare

Good test, If you check delete share test, not update share, we will get expected result. I think that ksmbd kernel server send tree connect ipc request to ksmbd.mountd. but ksmbd.mountd seems not to have updated share(MyShare) after updating parameters using ksmbd.addshare. We need to check this.

**Comment by namjaejeon** [comment]
> By the way, modprobe@.service was introduced in systemd v245 which was released 2020-03-06. Is this a problem?

Well, I think that we can add simple comment in README for this ? If it was two years ago, I don't think it would be much of a problem.

**Comment by atheik** [comment]
> > By the way, [modprobe@.service](mailto:modprobe@.service) was introduced in systemd v245 which was released 2020-03-06. Is this a problem?
> 
> Well, I think that we can add simple comment in README for this ? If it was two years ago, I don't think it would be much of a problem.

@namjaejeon, RHEL 7 and RHEL 8 (as well as the derivatives of those versions) have systemd v219 and v239, respectively. ELRepo is a third party that packages ksmbd-tools (and a compatible kernel) for those versions of RHEL and their derivatives.

**Comment by atheik** [comment]
> If you check delete share test, not update share, we will get expected result.

@namjaejeon, just to confirm, is the following behavior intended?

```sh
# following is ran in linux

sudo ksmbd.control --shutdown

mkdir -vp $HOME/MyShare

sudo ksmbd.addshare --config=$HOME/test.conf --add-share=MyShare --options="
path = $HOME/MyShare
read only = no
"

sudo ksmbd.adduser --import-users=$HOME/test.db --add-user=MyUser --password=''

sudo ksmbd.addshare --config=$HOME/test.conf --update-share=MyShare --options="
force user = $USER
force group = $USER
"

sudo ksmbd.mountd --config=$HOME/test.conf --users=$HOME/test.db

networkctl status | grep Address
#          Address: 192.168.1.105 on wlan0

# following is ran in termux on android

touch $HOME/file
smbclient --user=MyUser //192.168.1.105/MyShare
# smb: \>

# keep the smbclient prompt open

# following is ran in linux

sudo ksmbd.addshare --config=$HOME/test.conf --del-share=MyShare

sudo kill -HUP $(cat /tmp/ksmbd.lock)

# following is ran in termux on android

# smb: \> put file new_file_on_deleted_share

# following is ran in linux

ls -lah $HOME/MyShare
# total 8.0K
# drwxr-xr-x  2 atte atte 4.0K Jul 10 05:17 .
# drwx------ 22 atte atte 4.0K Jul 10 05:14 ..
# -rwxr--r--  1 atte atte    0 Jul 10 05:17 new_file_on_deleted_share

# deleting a share does not invalidate share access of users that are already connected
```

**Comment by namjaejeon** [comment]
@atheik Yes, This is the result we expected(i.e. not problem). The share that is already connected should be not invalidate by deleting share using ksmbd.addshare. It should use old share config. The new connection should only use updated share or share list.

**Comment by atheik** [comment]
@namjaejeon, I have updated this PR. I added minimum version checks to the meson build so as to have parity with the autotools build. Also, I made it so that the unit file is only installed automatically for systemd versions 245 and greater. I added a mention of this to the README. I moved removing `scripts/install.sh` to `ksmbd-tools: install systemd unit file when applicable` since it is more relevant there. Should the `--update-share` bug regarding `SIGHUP` be fixed in this PR?

**Comment by namjaejeon** [comment]
> Should the --update-share bug regarding SIGHUP be fixed in this PR?

No, I will apply this PR without this. Free free to fix it on next PR:)

**Comment by sergey-senozhatsky** [comment]
Sorry, couldn't reply over weekend.

> So if a share is deleted, it can still be accessed as long as someone has it mounted, right?

Right. And I suspect even more - new connections can still succeed, because they will use ksmb cached share config.

**Comment by sergey-senozhatsky** [comment]
> Yes, This is the result we expected(i.e. not problem). The share that is already connected should be not invalidate by deleting share using ksmbd.addshare. It should use old share config. The new connection should only use updated share or share list.

We need to disable share config caching maybe. I suspect that new connections will keep using cached share config.

**Review by sergey-senozhatsky — APPROVED** [review]

**Comment by namjaejeon** [comment]
@sergey-senozhatsky Thanks for your approval!

@atheik Applied, Thanks for your patch!

**Comment by atheik** [comment]
@namjaejeon, @sergey-senozhatsky,

A new connection is handled at kernelspace at `ksmbd_tree_conn_connect()`.
`ksmbd_share_config_get()` is called to get the config.
https://github.com/cifsd-team/ksmbd/blob/66008b2/mgmt/tree_connect.c#L28

`ksmbd_share_config_get()` calls `__get_share_config()` to get a cached share config.
A cached share config is available if there is at least one active connection to the share.
https://github.com/cifsd-team/ksmbd/blob/66008b2/mgmt/share_config.c#L206
https://github.com/cifsd-team/ksmbd/blob/66008b2/mgmt/share_config.c#L63-L69
Only if there is no cached share config, `ksmbd_share_config_get()` calls `share_config_request()`.
https://github.com/cifsd-team/ksmbd/blob/66008b2/mgmt/share_config.c#L209-L211

The changes done with `--update-share` only apply when `ksmbd_share_config_get()` calls `share_config_request()`.
https://github.com/cifsd-team/ksmbd/blob/66008b2/mgmt/share_config.c#L125
https://github.com/cifsd-team/ksmbd-tools/blob/4608cd4/mountd/worker.c#L287-L289
https://github.com/cifsd-team/ksmbd-tools/blob/4608cd4/mountd/worker.c#L178
https://github.com/cifsd-team/ksmbd-tools/blob/4608cd4/lib/management/share.c#L759-L760

One way to fix this `--update-share` bug would be to remove the call to `__get_share_config()` and instead always
call `share_config_request()` at `ksmbd_share_config_get()`. This would disable cached share configs like @sergey-senozhatsky suggested.

So, I think this `--update-share` bug cannot be fixed at `ksmbd-tools`, it would have to be fixed at `ksmbd`.
Could you please check that my interpretation is correct?

> > So if a share is deleted, it can still be accessed as long as someone has it mounted, right?
> 
> Right. And I suspect even more - new connections can still succeed, because they will use ksmb cached share config.

@sergey-senozhatsky, here is why a new connection to a deleted share fails even if someone has it mounted.
Little bit after, `ksmbd_tree_conn_connect()` messages to userspace with `ksmbd_ipc_tree_connect_request()`.
This is not related to cached share config.
https://github.com/cifsd-team/ksmbd/blob/66008b2/mgmt/tree_connect.c#L49
https://github.com/cifsd-team/ksmbd-tools/blob/4608cd4/mountd/worker.c#L275-L277
https://github.com/cifsd-team/ksmbd-tools/blob/4608cd4/mountd/worker.c#L147
https://github.com/cifsd-team/ksmbd-tools/blob/4608cd4/lib/management/tree_conn.c#L65-L70

**Comment by namjaejeon** [comment]
@atheik Right, We should probably change both ksmbd and ksmbd.mountd.
ksmbd kernel server send two ipc request, share config(KSMBD_EVENT_SHARE_CONFIG_REQUEST) and tree connect (KSMBD_EVENT_TREE_CONNECT_REQUEST) to ksmbd.mountd. share config from share ip request can be cached in ksmbd kernel. but tree connect ipc request is not. tree connect ipc request is checking if share is in share list of ksmbd.mountd. So delete share option of ksmbd.mountd work well and update share option doesn't work. I think the update share option should mark that the share in the share list has been updated and the ksmbd server check tree connect response and know if share is updated. and ksmbd server send a share config request again after invalidating cached share config.

**Comment by atheik** [comment]
@namjaejeon, could you please do a preliminary review for these changes?
https://github.com/atheik/ksmbd/commit/49ff593
https://github.com/atheik/ksmbd-tools/commit/67e9568

**Comment by namjaejeon** [comment]
regarding to ksmbd change, We need to create stale_share_table and move stale share from share_table to stale_share_table not to be searched from new connection. and need to lock with down_write(shares_table_lock). and if we set ->refcount of old share to zero, It will be memory leak. please see ksmbd_share_config_put() function. Any thought ?

**Comment by namjaejeon** [comment]
@atheik  And you need to send these patches(ksmbd and ksmbd-tools) to the mailing list(linux-cifs@vger.kernel.org) to get review from other maintainers of ksmbd.

**Comment by atheik** [comment]
@namjaejeon,

> @atheik regarding to ksmbd change, We need to create stale_share_table and move stale share from share_table to stale_share_table not to be searched from new connection. and need to lock with down_write(shares_table_lock). and if we set ->refcount of old share to zero, It will be memory leak. please see ksmbd_share_config_put() function. Any thought ?

I temporarily set share refcount to zero to get this codepath from `ksmbd_share_config_get()`.
https://github.com/atheik/ksmbd/blob/5bdc57e/mgmt/share_config.c#L206
https://github.com/atheik/ksmbd/blob/5bdc57e/mgmt/share_config.c#L67
https://github.com/atheik/ksmbd/blob/5bdc57e/mgmt/share_config.c#L211
https://github.com/atheik/ksmbd/blob/5bdc57e/mgmt/share_config.c#L177
`hash_add()` at `share_config_request()` chooses a bucket with the share name hash. The updated share gets added as the head of the list at that bucket. `hash_for_each_possible()` iterates the list at the bucket in order so future `__share_lookup()`s return the latest updated share first. I made a careless mistake in https://github.com/atheik/ksmbd/commit/49ff593, where I didn't restore the stale share refcount properly (it remained 0) and the updated share had the stale share refcount. This might have been the cause of the memory leak you detected. I have now fixed this so that the updated share has refcount 1 and the stale share refcount is restored properly. Due to the aforementioned way the hash table works, I don't see the reason why stale shares would need a separate table.  I have now tested this and everything seems to work. Could you please also test this when you have the time?
https://github.com/atheik/ksmbd/commit/5bdc57e60659fb00f4a20601250acab60629c80e

> @atheik And you need to send these patches(ksmbd and ksmbd-tools) to the mailing list([linux-cifs@vger.kernel.org](mailto:linux-cifs@vger.kernel.org)) to get review from other maintainers of ksmbd.

I'll send the ksmbd and ksmbd-tools changes to the mailing list when I am certain the basic approach is correct.

**Comment by namjaejeon** [comment]
@atheik existing connection should use old share, not updated share. The updated shares should be only used with new connection. I am concerning racy issues when replacing share with updated share while running operations on existing connection.

**Comment by atheik** [comment]
@namjaejeon, thank you again for looking into this.

> @atheik existing connection should use old share, not updated share. The updated shares should be only used with new connection.

Existing connections do use the old share and not the updated share. The updated share is only used with new connections. Did you find a scenario where this is not the case?
> I am concerning racy issues when replacing share with updated share while running operations on existing connection.

After setting refcount to 0 and before it is restored, for the duration of `ksmbd_share_config_get()`, disconnect of an existing connection would mean that the old share refcount would be restored to the wrong value.
https://github.com/atheik/ksmbd/blob/5bdc57e/mgmt/tree_connect.c#L71-L73 
The only reason I temporarily set refcount to 0 is to get the aforementioned codepath for `ksmbd_share_config_get()`. Instead of doing this hacky trick for `ksmbd_share_config_get()`, it would be much better to write a new function. That would get rid of this particular racy issue. I will rewrite the ksmbd changes so that there is no need to touch the stale share refcount. Is this the racy issue you had in mind?

> You need to consider hash_del() call in __ksmbd_share_config_put() if you add updated share after deleting old share in share table.

` __ksmbd_share_config_put()` gets called for the old share when its refcount is decremented to 0. It gets decremented to 0 when all existing connections using it are disconnected. `hash_del()` then removes it from the share name specific bucket. This does not affect any possible more updated or more stale versions of the share still remaining in the bucket. I don't understand the issue.

**Comment by atheik** [comment]
@namjaejeon, please take a look when you have the time.
https://github.com/atheik/ksmbd/commit/3ce134b
https://github.com/atheik/ksmbd-tools/commit/d1de928

**Comment by namjaejeon** [comment]
> I will rewrite the ksmbd changes.

I think that we need to call ksmbd_share_config_put() instead of atomic_dec(). Please see the below change.

```
		}
-		atomic_dec(&stale_sc->refcount);
+              ksmbd_share_config_put(stale_sc);
	}
```

```
                                                                                 //  there is old share in share list. old share refcount is 2.
                                                                                 ksmbd_tree_conn_connect() -> ksmbd_share_config_get()
// tree_disconnect decrease refcount(2->1), but it is not zero. So old share is not killed.                                                              
-> tree_disconnect(old_share);
                                                                                ->atomic_dec(&stale_sc->refcount); //refcount is 0. but old share is not killed.(memory leak)

```


> the latest share is first and the stalest share is last. 

Ah, Okay. I concern this case. 
```
1. first connection is coming. there is old share in share list.
2. share is updated by ksmbd.addshare. new share flags is marked with update.
3. 2th connection is coming and ksmbd server request to get updated share to ksmbd.mountd. and ksmbd.mountd clear update mark of share.
4. 2th connection is disconnect before first connection. old share is still in share list.
5. 3th connection is coming and use old share. because update marking of share flags was clear.

```

**Comment by namjaejeon** [comment]
> Also, the old share is marked as stale at ksmbd_share_config_request() from ksmbd_tree_conn_connect().

Okay.

```
#define KSMBD_SHARE_FLAG_STALE			BIT(14)

	if (test_share_config_flag(share, KSMBD_SHARE_FLAG_STALE) ||
	    !atomic_inc_not_zero(&share->refcount))

		if (test_share_config_flag(share, KSMBD_SHARE_FLAG_UPDATE))
			lookup->flags |= KSMBD_SHARE_FLAG_STALE;
```

But the lines of code are getting more and more. If we remove old share in share list, there is no need to add such additional checks in other functions. only need to add the check to protect double hash_del calling in __ksmbd_share_config_put(). Let me know your thought.

**Comment by atheik** [comment]
@namjaejeon, Sure.
https://github.com/atheik/ksmbd/commit/2d64071
https://github.com/atheik/ksmbd-tools/commit/2bcd824

**Comment by atheik** [comment]
@namjaejeon, I don't think calling `hash_del()` twice on a node is a problem. The second one should be a nop. However, I did add a check as you requested.

**Pull request closed without merging**
