### PR TITLE
meson: run through muon analyze

### PR DESCRIPTION
**Pull request by neheb**
Mostly unused variable removals. Removed pointless [] in include_directories.

Removed excess ''' in run_command to make compatible with muon.

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by neheb** [comment]
there's another one:

```
/home/mangix/devstuff/ksmbd-tools/meson.build:103:53: error undefined option
103 |     runstatedir = get_option('prefix') / get_option('runstatedir')
```

but that can stay i think.

**Comment by eli-schwartz** [comment]
> Removed excess ''' in run_command to make compatible with muon.

Personally I just reported the muon bug to be fixed:

https://git.sr.ht/~lattis/muon/commit/9918e4d60dd531cacfb98ad4bc7f6223d1d1e094

**Comment by neheb** [comment]
OTOH the solution simplifies the run_command call.

**Comment by atheik** [comment]
@neheb,

> OTOH the solution simplifies the run_command call.

By having to escape single quotes in the string? Since this is just a workaround for a bug in muon, please don't change it. I want the version extraction to be identical in the autotools and meson builds. That's why the meson one runs awk through the shell.

**Comment by atheik** [comment]
> there's another one:
> 
> ```
> /home/mangix/devstuff/ksmbd-tools/meson.build:103:53: error undefined option
> 103 |     runstatedir = get_option('prefix') / get_option('runstatedir')
> ```
> 
> but that can stay i think.

Yes, that is guarded by:
```meson
if false # meson.version().version_compare('>= ')
```

Hopefully, some future version of meson will support `runstatedir`.

**Comment by namjaejeon** [comment]
@neheb @atheik 

Sorry, Can I apply this patch to #master ?

Thanks!

**Comment by atheik** [comment]
@namjaejeon, @neheb,

The `run_command()` change should be removed.

**Comment by namjaejeon** [comment]
@atheik Okay:)

**Comment by neheb** [comment]
Fixed.

**Comment by atheik** [comment]
@neheb,

The commit title prefix should be `ksmbd-tools: `, e.g. `ksmbd-tools: remove unused variables in meson build`.

**Comment by neheb** [comment]
Done.

**Review by atheik — APPROVED** [review]

**Comment by atheik** [comment]
@neheb, @namjaejeon,

Looks like the commit message still has this:
```
Removed excess ''' in run_command to make compatible with muon.
```
That change was removed.

**Comment by namjaejeon** [comment]
@atheik I will directly remove it. Thanks for pointing it out.

**Pull request closed without merging**
