### PR TITLE
ksmbd-tools: accept global share options

### PR DESCRIPTION
**Pull request by papadakospan**
Addresses cifsd-team/ksmbd#516

Signed-off-by: Leonidas P. Papadakos \<papadakospan@gmail.com\>

### CODE REVIEW

**Comment by namjaejeon** [comment]
There is the patch to add .gitignore in your PR. Do you want to apply .gitignore patch to ksmbd-tools ?

**Comment by papadakospan** [comment]
Yes, I think it's a good idea and it helps with git not picking up a ton of files that autotools generate

**Comment by papadakospan** [comment]
I only slightly modified the .gitignore from [templates provided by GitHub](https://github.com/github/gitignore). If you want the comments to be shorter or non-existent, it can be arranged.

Also, since I need to change the patch subject, do I need to create a new branch in my fork, commit there and make a new pull request, or am I over-complicating it?

**Comment by papadakospan** [comment]
I have addressed the issues you mentioned. The push I did only affected my fork of the project. I now have 2 commits that each do 2 wanted things. If it creates problems with merging and it is necessary to create a new PR, you can inform me here

**Comment by namjaejeon** [comment]
1. flags argument of g_hash_table_foreach doesn't seem necessary anymore. It seems to be possible to pass NULL.
```
+               global_group = g_hash_table_lookup(parser.groups, "global");
+
+               if (global_group && (flags == GROUPS_CALLBACK_STARTUP_INIT))
+                       global_conf_create();
+
                g_hash_table_foreach(parser.groups,
                                     groups_callback,
                                     (gpointer)flags);
```

2. Please see warnings from checkpatch.pl.
```
ERROR: Bad function definition - void global_conf_create() should probably be void global_conf_create(void)
#220: FILE: lib/config_parser.c:568:
+static void global_conf_create()

WARNING: Block comments use a trailing */ on a separate line
#224: FILE: lib/config_parser.c:572:
+	 * share */

ERROR: open brace '{' following function definitions go on the next line
#242: FILE: lib/config_parser.c:614:
+static void append_key_value(gpointer _k, gpointer _v, gpointer user_data) {

total: 2 errors, 1 warnings, 276 lines checked
```

**Comment by namjaejeon** [comment]
Okay, Looks good, But you need to merge "ksmbd-tool: config_parser checkpatch.pl fixes" into "ksmbd-tools: accept global share options".

**Comment by papadakospan** [comment]
Is this ok to merge now?

**Comment by namjaejeon** [comment]
Looks good to me, applied!, I will also send these patches to the mailing list if there may be other reviews.

**Comment by namjaejeon** [comment]
I have manually pushed the patches to #master. You can check the applied patches on #master branch. Thanks for your work!

**Pull request closed without merging**
