### PR TITLE
add some g_free to match g_ alloc functions

### PR DESCRIPTION
**Pull request by neheb**
ping @atheik

### CODE REVIEW

**Comment by atheik** [comment]
@neheb,

Please prefix commit titles with `ksmbd-tools: `. Would you rename `add 0 to g_try_malloc` to something descriptive, e.g. `ksmbd-tools: fix missing zeroing in lsarpc_ph_alloc()`? Please also rename and mention commit fd007c7 in `add some g_free to match g_ alloc functions` as well since its specifically about using `g_free()` for allocations added in that commit.

**Comment by atheik** [comment]
@namjaejeon,

Please see https://github.com/cifsd-team/ksmbd-tools/pull/242#pullrequestreview-1131920319.

**Comment by neheb** [comment]
Done.

btw what do you think about https://github.com/neheb/ksmbd-tools/commit/089b205d709efc16afc147949f20c725dbd4c0a6 ?

Avoids some of this mess I think.

**Comment by atheik** [comment]
@neheb,

> btw what do you think about [neheb@089b205](https://github.com/neheb/ksmbd-tools/commit/089b205d709efc16afc147949f20c725dbd4c0a6) ?

In this codebase, declarations are always at the top of the block. `g_autofree` is implemented using `__attribute__((cleanup))` which triggers only when the variable goes out of scope. With mixed declarations and code, as in your commit [neheb@089b205](https://github.com/neheb/ksmbd-tools/commit/089b205d709efc16afc147949f20c725dbd4c0a6), if there is `goto` which jumps over a `g_autofree` variable declaration (and initialization), `g_free()` will be called for an uninitialized variable when leaving that scope. When declaring a `g_autofree` variable at the top of the block, we need to only worry that such variables are always initialized to `NULL`.

It would be nice to avoid using the GLib types which are just typedefs to standard C types or pointers to them. A few have already snuck into some places in this codebase, e.g. `gpointer`, `gconstpointer`, `gchar`, `guint`, and `gint`. I would like to suggest removing them in the future.

In your [neheb@089b205](https://github.com/neheb/ksmbd-tools/commit/089b205d709efc16afc147949f20c725dbd4c0a6), doesn't `open_m` at `create_lock_file()` leak when `goto retry` is reached and then `open_m = g_strdup_printf("%m")` is reached for a second time? 

> Avoids some of this mess I think.

It does look cleaner. However, it also makes any future GLib removal effort more difficult.

**Comment by neheb** [comment]
@atheik I don't think there's a memory leak. I've tested with both gcc's -fanalyzer (which caught an oversight on my part) and clang-analyzer. Both don't see anything.

glib removal is interesting. It can be linked statically and compiled with -flto , wiping away a lot of compiled size. Last time it was attempted it was rejected as rewriting some glib functionality (I think relating to atomics) is problematic. I don't know if there's a desire to do so.

**Comment by atheik** [comment]
@neheb,

> @atheik I don't think there's a memory leak. I've tested with both gcc's -fanalyzer (which caught an oversight on my part) and clang-analyzer. Both don't see anything.
> 

Well, in your [neheb@089b205](https://github.com/neheb/ksmbd-tools/commit/089b205d709efc16afc147949f20c725dbd4c0a6), if `open_m = g_strdup_printf("%m")` is reached a second time in a single `create_lock_file()` call, through `goto retry`, then where is the first allocation freed? There is a memory leak. You can't delegate this thinking to static analyzers. This is essentially the same leak, verifiable with Valgrind:
```sh
cat <<'EOF' >a.c
#include <glib.h>

int main(void)
{
	g_autofree char *cp = NULL;
	int cnt = 2;

retry:
	if (cnt--) {
		cp = g_strdup("");
		/*
		g_free(cp);
		cp = NULL;
		*/
		goto retry;
	}
}
EOF

gcc a.c -fanalyzer -g -O0 $(pkg-config --cflags --libs glib-2.0)
valgrind --leak-check=full ./a.out

```

`g_autofree` is implemented using `__attribute__((cleanup))` which triggers only when the variable goes out of scope.

@neheb, @namjaejeon,

> glib removal is interesting. It can be linked statically and compiled with -flto , wiping away a lot of compiled size.

I am aware of that. By the way, if you have an OpenWRT build environment available, could you do such a build of `ksmbd-tools` (`master`) and compare the utility sizes to the 3.4.5 release. Since we now use `g_utf8_casefold()`, `casefold_table` (generated from Unicode data with `glib/gen-unicode-tables.pl`) gets statically linked in, which should increase the utility sizes somewhat.

> Last time it was attempted it was rejected as rewriting some glib functionality (I think relating to atomics) is problematic. I don't know if there's a desire to do so.

I don't know whether it is desirable either. That is something for the maintainer to decide.

Currently, this codebase is partially GLibified. There are unused OOM error paths for `g_hash_table_new()`, `g_array_new()`, `g_base64_decode()`, `g_strdup()`, `g_strndup()`, `g_strdup_printf()`, and `g_thread_pool_new()` calls, all of which abort on OOM and do not return `NULL`. For some of them, allocations are wrongly freed with `free()` instead of `g_free()`. There are also some remaining `malloc()` (and `free()`) calls which should be replaced with `g_try_malloc()` (and `g_free()`) for the sake consistency. For the few uses of `strdup()` (and `strndup()`) remaining, we should check their OOM error paths and determine whether it is OK to abort instead and so use `g_strdup()` (and `g_strndup()`). As for GLib typedefs of standard C types (e.g. `gpointer`, `guint`, ...), it would be nice to get rid of them. I would like to contribute these changes.

**Comment by namjaejeon** [comment]
@atheik @neheb 

> if you have an OpenWRT build environment available, could you do such a build of ksmbd-tools (master) and compare the utility sizes to the 3.4.5 release.

That's a good point. We should check it out before releasing ksmbd-tools.

**Comment by neheb** [comment]
@namjaejeon 

```
-rw-r--r--. 1 mangix mangix 73724 Oct  6 17:47 bin/packages/mips64el_mips64r2/packages/ksmbd-server_3.4.5-7_mips64el_mips64r2.ipk
-rw-r--r--. 1 mangix mangix 41100 Oct  6 17:47 bin/packages/mips64el_mips64r2/packages/ksmbd-utils_3.4.5-7_mips64el_mips64r2.ipk
mangix@ryzen ~/d/openwrt (mangix)> ls -Rl bin/packages/mips64el_mips64r2/packages/ksmbd-*
-rw-r--r--. 1 mangix mangix 119573 Oct  6 17:56 bin/packages/mips64el_mips64r2/packages/ksmbd-server_3.4.6-1_mips64el_mips64r2.ipk
-rw-r--r--. 1 mangix mangix  95056 Oct  6 17:56 bin/packages/mips64el_mips64r2/packages/ksmbd-utils_3.4.6-1_mips64el_mips64r2.ipk
```

the utils reduction is from some documentation.txt file removal. 3.4.6 is current master.

Obviously it's smaller with 32-bit targets. this is a 64-bit one. I'm guessing the relative change is what's relevant here.

**Comment by namjaejeon** [comment]
@neheb Applied, Thanks for your patch!

**Pull request closed without merging**
